<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-DL42SBL" failures="2" tests="2" name="Default test(failed)(failed)" time="0.071" errors="0" timestamp="2023-05-15T20:32:00 EDT">
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestFive" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.hooks.FailedTestCases.getTestFive(FailedTestCases.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestFive -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestOne" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at smarttech.ny.hooks.FailedTestCases.getTestOne(FailedTestCases.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTestOne -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestTwo" time="0.0">
    <ignored/>
  </testcase> <!-- getTestTwo -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestFour" time="0.0">
    <ignored/>
  </testcase> <!-- getTestFour -->
  <testcase classname="smarttech.ny.hooks.FailedTestCases" name="getTestThree" time="0.0">
    <ignored/>
  </testcase> <!-- getTestThree -->
</testsuite> <!-- Default test(failed)(failed) -->
